### ISSUE TITLE
Include Bower and Browserify in the list.

### ISSUE THREAD

**Issue by Rupeshiya** [Rupeshiya/npmGuider#3]

**Comment by debck** [comment]
Hey @Rupeshiya I too raised the same issue ....u never responded ....😜😜😜😜

**Comment by Rupeshiya** [comment]
@debck I ve seen that you closed the issue thats why I created this issue bro...
You can make changes to the file and send PR 😅😅😅😉😉😜

**Comment by debck** [comment]
Okay ...thanx .. @Rupeshiya sir ..😂😂

**Comment by Rupeshiya** [comment]
This is fixed by @debck  sir by PR  #4 .
